#!/bin/bash
cd /home/ec2-user/ruby-sinatra
if ! gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB ; then
    curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
fi
curl -sSL https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.5.3 --disable-binary
gem install -N sinatra
gem install -N json
gem install -N bundler
yum install -y ruby-devel
gem install -N io-console
bundle install
bundle exec rackup -p 80 -o 0.0.0.0 -D
